backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", required: true, widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", required: true, widget: "markdown" }
